export const types = {

    login: '[Auth] Login',
    logout: '[Auth] Logout',

    uiSetError: '[UI] Set Error',
    uiSetCorrect: '[UI] Set Correct',
    uiRemoveError: '[UI] Remove Error',
    uiStartLoading: '[UI] Start loading',
    uiFinishLoading: '[UI] Finish loading',
    uiStartLoadingCards: '[UI] Start loading cards',
    uiFinishLoadingCards: '[UI] Finish loading cards',
    uiSetActiveScreen: '[UI] Set active Screen',
    uiOpenDropMenu: '[UI] Open drop menu',
    uiCloseDropMenu: '[UI] Close drop menu',

    authCheckingStart: '[auth] Start checking login state',
    authCheckingFinish: '[auth] Finish checking login state',
    authStartLogin: '[auth] Start login',
    authLogin: '[auth] Login',
    authStartRegister: '[auth] Start Register',
    authStartTokenRenew: '[auth] Start token renew',
    authLogout: '[auth] Logout',

    formsGetStudents: '[forms] Get Students',
    formsGetCampus: '[forms] Get Campus',
    formsGetMajors: '[forms] Get Majors',
    formsGetGroups: '[forms] Get Groups',
    formsGetDepartaments: '[forms] Get Departaments',
    formsGetPersonal: '[forms] Get Personal',
    formsGetScholarships: '[forms] Get Scholarships',
    formsGetCourses: '[forms] Get Courses',
    formsGetTeachers: '[forms] Get Teachers',

    formsNewError: '[forms] New Errors',
    formsCleanErrors: '[forms] Clean Errors',
    formsSetActive: '[forms] Set Active',
    formsClearActive: '[forms] Clear Active',


    formsAddData: '[forms] Add Data',
    formsDeleteStudents: '[forms] Delete Data Students',

    panelSetData: '[panel] Set Data',
    panelAddData: '[panel] Add Data',
    panelUpdateData: '[panel] Update Data',
    panelDeleteData: '[panel] Delete Data',
    panelClearData: '[panel] Clear Data',

    paySetActive: '[pay] Set Active',
    paySetCards: '[pay] Set Cards',
    paySetPrice: '[pay] Set Price',
    payClearActive: '[pay] Clear Active',
    payConceptPay: '[pay] Concept pay',
    payMethodPay: '[pay] Method pay',
    payThingToPay: '[pay] Material to pay',
    payClearModalData: "[pay] Clear modal data",
    payAmountToPay: "[pay] Set amount paying",
    paySetActiveAccount: "[pay] Set Active Acount",
    paySetFertilizers: "[pay] Set fertilizers",
    paySetIdPayment: "[pay] Set id payment",
    paySetPayments: '[pay] Set payments',
}